### PR TITLE
Support fontFamily arrays and put a notice about funky fontSize settings.

### PR DESCRIPTION
**Pull request by crswll**

### CODE REVIEW

**Comment by matildepark** [comment]
Is this ready? I seem to have hit a bug contingent on the work in here.

**Comment by crswll** [comment]
Hey. I think so. I'll try to get it merged and published later on today. Having a hard time recalling why I didn't merge it at the moment.

**Comment by matildepark** [comment]
Cool, thanks.

**Comment by matildepark** [comment]
Any luck?

**Comment by god-of-javascript** [comment]
Any updates?

**Pull request merged**
